
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nshamann-nginx-3k-depl
  labels:
    app: nshamann-nginx-3k
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nshamann-nginx-3k
  template:
    metadata:
      labels:
        app: nshamann-nginx-3k
    spec:
      containers:
      - name: nshamann-nginx-3k
        image: nshamann/nginx-3k:latest
        ports:
        - containerPort: 80
        
---            
apiVersion: v1
kind: Service
metadata:
  name: nshamann-nginx-3k-service
spec:
  type: NodePort
  selector:
    app: nshamann-nginx-3k
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200
  type: LoadBalancer        